import Head from 'next/head'
import { Inter } from 'next/font/google'
import InstallMaps from '@/components/InstallMaps'
import { Box, Grid } from '@mui/material'
import requestData from '@/API/Quickbase'
import { useEffect, useState } from 'react'
import { useRouter } from 'next/router'

const API_URL = "https://api.quickbase.com/v1/records/query";
const USER_TOKEN = "QB-USER-TOKEN b7738j_qjt3_0_dkaew43bvzcxutbu9q4e6crw3ei3";
const QB_DOMAIN = "voltaic.quickbase.com";

export default function Portal() {

  const router = useRouter()
  const {id} = router.query;

  
  const handleButtonClick = async () => {
    try {
      const response = await requestData();
      setData(response.data);
    } catch (error) {
      console.error(error);
    }
  };

  const [data, setData] = useState([]);



  return (
    <>
      <Head>
        <title>Voltaic Install Map</title>
        <meta name="description" content="Voltiac OPS" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box sx={{ height: '100vh', width:'100vw', backgroundColor: 'black', p: 2, color: 'white' }}>
        {/* <InstallMaps /> */}
        <h1>
         Portal # {id}
        </h1>
      </Box>

    </>
  )
}





// <Grid container spacing={2} sx={{backgroundColor: 'black', color: 'white'}}>
//         <Grid item xs={12} md={6}>
//           <Box sx={{ height: '70vh', backgroundColor: 'black', color: 'black',p: 2, fontWeight: 'bold' }}>
//             <InstallMaps />
//           </Box>
//         </Grid>

//         <Grid item xs={12} md={6}>
//           <Box sx={{ height: '70vh', backgroundColor: 'black', p: 2 ,color: 'white'}}>
//             <h2>List Preview</h2>
//             <ul>
//               {items.map((item) => (
//                 <li key={item.id}>
//                   <img src={item.imageUrl} alt={item.title} />
//                   <div>
//                     <h3>{item.title}</h3>
//                     <p>{item.subject}</p>
//                   </div>
//                 </li>
//               ))}
//             </ul>
//           </Box>
//         </Grid>

//         <Grid item xs={12}>
//           <Box sx={{ height: '30vh', backgroundColor: 'black', p: 2  ,color: 'white'}}>
//             <h2>Charts</h2>
//             <Box sx={{ display: 'flex', justifyContent: 'space-around'  ,color: 'white'}}>
//               <Box sx={{ width: '40%' }}>
//               <p> Line Chart</p>
//                 {/* <LineChart data={[5, 10, 8, 15, 12, 7, 10]} /> 
                
//               </Box>
//               <Box sx={{ width: '40%' }}>

//                 <p> Bar Chart</p>
//                 {/* <BarChart data={[3, 8, 2, 10, 5, 6, 9]} /> */}
//               </Box>
//             </Box>
//           </Box>
//         </Grid>
//       </Grid> 




// // import Head from 'next/head'
// // import { Inter } from 'next/font/google'
// // import InstallMaps from '@/components/InstallMaps'
// // import { Box } from '@mui/material'


// // export default function Home() {
// //   return (
// //     <>
// //       <Head>
// //         <title>Create Next App</title>
// //         <meta name="description" content="Generated by create next app" />
// //         <meta name="viewport" content="width=device-width, initial-scale=1" />
// //         <link rel="icon" href="/favicon.ico" />
// //       </Head>
// //             <Box sx={{
// //                 display: 'flex', 
// //                 justifyContent: 'center' , 
// //                 height: '100vh',
// //                 width: '100vw', 
// //                 backgroundColor: 'black',
// //                 justifyContent: 'left',
// //                 paddingLeft: '20px',
// //                 paddingTop: '20px',
                
// //        }}>
              

// //               <Box sx={{width: '50vw', height: '50vh'}}> 
// //               <InstallMaps/>
// //               </Box>

       

// //       </Box>
// //     </>
// //   )
// // }
