import Head from "next/head";
import { useRouter } from 'next/router';
import styles from "@/styles/Home.module.css";
import HomeScreen from "@/components/page/HomePage";

import LoginDashboard from "@/components/page/LoginDashboard";

export default function Home() {
  const router = useRouter();
  const { id } = router.query;

  // Check if the password parameter is present
  const isValidPassword = id != null;

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {isValidPassword ? (
          <HomeScreen />
        ) : (
          <LoginDashboard />
        )}
      </main>
    </>
  );
}
