import Head from 'next/head'
import { Inter } from 'next/font/google'
import InstallMaps from '@/components/InstallMaps'
import { useQuery } from '@apollo/client'
import { Box, Grid } from '@mui/material'
import requestData from '@/API/Quickbase'
import { useEffect, useState } from 'react'
import { GET_MAP_DATA } from '@/gql/mutations/InstallMap'



export default function Home() {


  const { loading, error, data } = useQuery(GET_MAP_DATA);


  console.log("GraphQL Data:", data); // Add this line


  const formatDataForMarkers = (mapData) => {
    return mapData.map(item => ({
      color: item.color,
      position: {
        lat: parseFloat(item.position.lat.replace(/"/g, '')),
        lng: parseFloat(item.position.lng.replace(/"/g, '')),
      },
      label: {
        text: item.label.text.replace(/"/g, ''),
        color: item.label.color,
      },
      image: {
        url: "https://example.com/default-image.jpg", // Replace with the actual image URL
        alt: "Marker Image",
      },
      // Add other fields as needed
    }));
  };
  



  console.log("Formatted Data:", formatDataForMarkers); // Add this line



  const markers = loading ? [] : (data?.GetMapData ? formatDataForMarkers(data.GetMapData) : []);


  

  return (
    <>
      <Head>
        <title>Voltaic Install Map</title>
        <meta name="description" content="Voltiac OPS" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box sx={{ height: '100vh', width:'100vw', backgroundColor: 'black', p: 2, color: 'black' }}>
        <InstallMaps markers={markers} />
      </Box>

    </>
  )
}





// <Grid container spacing={2} sx={{backgroundColor: 'black', color: 'white'}}>
//         <Grid item xs={12} md={6}>
//           <Box sx={{ height: '70vh', backgroundColor: 'black', color: 'black',p: 2, fontWeight: 'bold' }}>
//             <InstallMaps />
//           </Box>
//         </Grid>

//         <Grid item xs={12} md={6}>
//           <Box sx={{ height: '70vh', backgroundColor: 'black', p: 2 ,color: 'white'}}>
//             <h2>List Preview</h2>
//             <ul>
//               {items.map((item) => (
//                 <li key={item.id}>
//                   <img src={item.imageUrl} alt={item.title} />
//                   <div>
//                     <h3>{item.title}</h3>
//                     <p>{item.subject}</p>
//                   </div>
//                 </li>
//               ))}
//             </ul>
//           </Box>
//         </Grid>

//         <Grid item xs={12}>
//           <Box sx={{ height: '30vh', backgroundColor: 'black', p: 2  ,color: 'white'}}>
//             <h2>Charts</h2>
//             <Box sx={{ display: 'flex', justifyContent: 'space-around'  ,color: 'white'}}>
//               <Box sx={{ width: '40%' }}>
//               <p> Line Chart</p>
//                 {/* <LineChart data={[5, 10, 8, 15, 12, 7, 10]} /> 
                
//               </Box>
//               <Box sx={{ width: '40%' }}>

//                 <p> Bar Chart</p>
//                 {/* <BarChart data={[3, 8, 2, 10, 5, 6, 9]} /> */}
//               </Box>
//             </Box>
//           </Box>
//         </Grid>
//       </Grid> 




// // import Head from 'next/head'
// // import { Inter } from 'next/font/google'
// // import InstallMaps from '@/components/InstallMaps'
// // import { Box } from '@mui/material'


// // export default function Home() {
// //   return (
// //     <>
// //       <Head>
// //         <title>Create Next App</title>
// //         <meta name="description" content="Generated by create next app" />
// //         <meta name="viewport" content="width=device-width, initial-scale=1" />
// //         <link rel="icon" href="/favicon.ico" />
// //       </Head>
// //             <Box sx={{
// //                 display: 'flex', 
// //                 justifyContent: 'center' , 
// //                 height: '100vh',
// //                 width: '100vw', 
// //                 backgroundColor: 'black',
// //                 justifyContent: 'left',
// //                 paddingLeft: '20px',
// //                 paddingTop: '20px',
                
// //        }}>
              

// //               <Box sx={{width: '50vw', height: '50vh'}}> 
// //               <InstallMaps/>
// //               </Box>

       

// //       </Box>
// //     </>
// //   )
// // }
