import Head from 'next/head'
import { Inter } from 'next/font/google'
import InstallMaps from '@/components/InstallMaps'
import { Box, Grid } from '@mui/material'
// import { LineChart, BarChart } from 'mui-charts'

const items = [
  {
    id: 1,
    title: "Item 1",
    subject: "Subject 1",
    imageUrl: "https://via.placeholder.com/150"
  },
  {
    id: 2,
    title: "Item 2",
    subject: "Subject 2",
    imageUrl: "https://via.placeholder.com/150"
  },
  {
    id: 3,
    title: "Item 3",
    subject: "Subject 3",
    imageUrl: "https://via.placeholder.com/150"
  }
];

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>



      <Box sx={{ height: '100vh', width:'100vw', backgroundColor: 'black', p: 2, color: 'white' }}>
        <InstallMaps />
        </Box>

    </>
  )
}






// <Grid container spacing={2} sx={{backgroundColor: 'black', color: 'white'}}>
//         <Grid item xs={12} md={6}>
//           <Box sx={{ height: '70vh', backgroundColor: 'black', color: 'black',p: 2, fontWeight: 'bold' }}>
//             <InstallMaps />
//           </Box>
//         </Grid>

//         <Grid item xs={12} md={6}>
//           <Box sx={{ height: '70vh', backgroundColor: 'black', p: 2 ,color: 'white'}}>
//             <h2>List Preview</h2>
//             <ul>
//               {items.map((item) => (
//                 <li key={item.id}>
//                   <img src={item.imageUrl} alt={item.title} />
//                   <div>
//                     <h3>{item.title}</h3>
//                     <p>{item.subject}</p>
//                   </div>
//                 </li>
//               ))}
//             </ul>
//           </Box>
//         </Grid>

//         <Grid item xs={12}>
//           <Box sx={{ height: '30vh', backgroundColor: 'black', p: 2  ,color: 'white'}}>
//             <h2>Charts</h2>
//             <Box sx={{ display: 'flex', justifyContent: 'space-around'  ,color: 'white'}}>
//               <Box sx={{ width: '40%' }}>
//               <p> Line Chart</p>
//                 {/* <LineChart data={[5, 10, 8, 15, 12, 7, 10]} /> 
                
//               </Box>
//               <Box sx={{ width: '40%' }}>

//                 <p> Bar Chart</p>
//                 {/* <BarChart data={[3, 8, 2, 10, 5, 6, 9]} /> */}
//               </Box>
//             </Box>
//           </Box>
//         </Grid>
//       </Grid> 




// // import Head from 'next/head'
// // import { Inter } from 'next/font/google'
// // import InstallMaps from '@/components/InstallMaps'
// // import { Box } from '@mui/material'


// // export default function Home() {
// //   return (
// //     <>
// //       <Head>
// //         <title>Create Next App</title>
// //         <meta name="description" content="Generated by create next app" />
// //         <meta name="viewport" content="width=device-width, initial-scale=1" />
// //         <link rel="icon" href="/favicon.ico" />
// //       </Head>
// //             <Box sx={{
// //                 display: 'flex', 
// //                 justifyContent: 'center' , 
// //                 height: '100vh',
// //                 width: '100vw', 
// //                 backgroundColor: 'black',
// //                 justifyContent: 'left',
// //                 paddingLeft: '20px',
// //                 paddingTop: '20px',
                
// //        }}>
              

// //               <Box sx={{width: '50vw', height: '50vh'}}> 
// //               <InstallMaps/>
// //               </Box>

       

// //       </Box>
// //     </>
// //   )
// // }
